name: .NET Build

on:
  pull_request:
    types: [closed]
    branches:   
      - Feature1
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  
run-name: Build from ${{ github.ref_name }} with Sonar and Fortify

jobs:
  if_PR_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was merged
        
  Build:
    needs: if_PR_merged
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
           echo "dotnet build"
      
    - name: sonar
      run: |
           echo Sonar
  Fortify:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
    - name: Fortify
      run: |
           echo "Fortify-test"
    
     
  Upload_Artifact_GitHub_Release:         
       runs-on: ubuntu-latest
       needs: [Build,Fortify]  
       steps:
         - run: echo test
