name: .NET Build

on:
  pull_request:
    types: [closed]
    branches:   
      - Feature1
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  actions: read
  id-token: write
  
run-name: Build from ${{ github.ref_name }} 

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Build
      run: |
           echo "dotnet build --no-restore"
      
    - name: sonar
      run: |
           echo Sonar
  Fortify:
    runs-on: ubuntu-latest
    steps:
    - name: Fortify
      run: |
           echo "Fortify"
    
     
  Upload_Artifact_GitHub_Release:
         
       runs-on: ubuntu-latest
       needs: [Build,Fortify]
       
       steps:
       
         - run: echo test
