name: .NET Build

on:
  workflow_dispatch:
  
jobs:
  Build:
    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Package creation
      run: |
           mkdir sample_test
           mv ./bin/Debug/netcoreapp2.2/* ./sample_test
                    
    - name: Upload a Build Artfifact
      uses: actions/upload-artifact@v2
      with:
        name: sample_test
        path: ./sample_test
        retention-days: 1
      
  sonar:
     name: Sonar Analysis
     needs: Build
     uses: ./.github/workflows/sonar.yml
     
  Upload_Artifact_GitHub_Release:
         
       runs-on: ubuntu-latest
       needs: [Build,sonar]
       permissions:
          contents: write
          packages: write
       
       steps:
       
         - uses: actions/checkout@v3   
         
         - run: mkdir test
         
         - name: Dowload a Build Artfifact
           uses: actions/download-artifact@v2
           with:
             name: sample_test
             path: ./test
             
         - run : 7z a test.zip ./test
         
         - name: Create Github Release
           id: create_release
           uses: actions/create-release@v1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
           with:
             tag_name: test
             release_name: sample-test
             
         - name: Upload Artifacts to Github Release
           uses: actions/upload-release-asset@v1
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
           with:
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./test.zip
              asset_name: sample_test.zip
              asset_content_type: application/zip
     
#   upload:
#     runs-on: windows-latest
#     needs: [Build,sonar]
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Authenticate to GitHub Actions
#       run: dotnet nuget add source --username shiyamsundark --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/shiyamsundark/index.json"

#     - name: Pack Package
#       run: dotnet pack --configuration Release 
      
#     - name: Publish Package
#       run: dotnet nuget push "bin/Release/Helloworld.${{needs.Pre-Release.outputs.currentversion}}.nupkg" --source "github"
     
     
 
