name: STG test approval

on:
  workflow_dispatch:
 
jobs:
  
  Build:
    runs-on: ubuntu-latest

    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
  STG_Deploy_Approval_IT_Team:
   runs-on: ubuntu-latest
   needs: Build
   environment: STG
   steps:
   
      - name: IT Team's Approval
        run: echo "Approved from IT team..Passing for Devops approval.."
        
  STG_Deploy_Approval_Devops_Team:
   runs-on: ubuntu-latest
   needs: [Build,STG_Deploy_Approval_IT_Team]
   environment: Devops
   steps:
   
      - name: Devops Team's Approval
        run: echo "Approved from Devops team..Continuing with Deployment.."
        
  STG_Deploy:
      needs: [Build,STG_Deploy_Approval_IT_Team,STG_Deploy_Approval_Devops_Team]
      name: Deployment
      uses: ./.github/workflows/deploy.yml
