name: Sonar Analysis
on:
  workflow_dispatch:

jobs:
   

  - name: Send mail
    uses: dawidd6/action-send-mail@v3
    with:
      server_address: smtp.office365.com
      server_port: 587
      username: 
      password: 
      subject: Github Actions job result
      to:
      from:
      body: "Build job of ${{github.repository}} completed successfully!"
 





